name: Facebook Agent

on:
  workflow_dispatch:
  schedule:
    - cron: '0,22 8 * * *'     # 08:00 & 08:15 sáng (giờ VN)
    # - cron: '0 13 * * *'    # 20:00 tối (giờ VN)
  
jobs:
  agent-fb-posting:
    name: 'Agent Facebook Posting'
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout github repository'
        uses: actions/checkout@v4

      - name: 'set up python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
        
      - name: 'install library'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then 
            pip install -r requirements.txt;
          fi
      
      - name: 'run python'
        env:
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
          BLOCKED_DOMAINS: ${{ secrets.BLOCKED_DOMAINS }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          VERIFY_TOKEN: ${{ secrets.VERIFY_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
          MODEL: ${{ secrets.MODEL }}
        run: python fb_post.py

